version: '3.8'

services:
  redis:
      image: redis
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
  bot:
    build: .
    container_name: bot
    command: bash -c "python app.py"

volumes:
    redis-data: