name: Build and Deploy Docker Image

on:
  push:
    branches:
      - test
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Git Repository
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          script: |
            cd test_bot
            rm -rf Emphatix
            git clone https://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@github.com/MaxSheptyakov/Emphatix.git --branch test
            cp ~/test_bot/bot.ini ~/test_bot/Emphatix
            # docker stop bot 
            # docker container prune -f && docker image prune -f && docker volume prune -f && docker network prune -f
            cd Emphatix && docker compose up --build -d
            

